# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x99\x01\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\r\n\x05top_k\x18\x05 \x01(\x05\x12\x16\n\x0estop_sequences\x18\x06 \x03(\t\x12\x17\n\x0freturn_logprobs\x18\x07 \x01(\x08\"|\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08logprobs\x18\x02 \x03(\x02\x12\x18\n\x10tokens_generated\x18\x03 \x01(\x05\x12\x1a\n\x12generation_time_ms\x18\x04 \x01(\x02\x12\x12\n\nmodel_name\x18\x05 \x01(\t\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xb1\x01\n\x13HealthCheckResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.inference.HealthCheckResponse.Status\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x1a\n\x12gpu_memory_used_gb\x18\x03 \x01(\x02\"3\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\xa1\x01\n\x0cLLMInference\x12\x43\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\x12L\n\x0bHealthCheck\x12\x1d.inference.HealthCheckRequest\x1a\x1e.inference.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=31
  _globals['_GENERATEREQUEST']._serialized_end=184
  _globals['_GENERATERESPONSE']._serialized_start=186
  _globals['_GENERATERESPONSE']._serialized_end=310
  _globals['_HEALTHCHECKREQUEST']._serialized_start=312
  _globals['_HEALTHCHECKREQUEST']._serialized_end=349
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=352
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=529
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=478
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=529
  _globals['_LLMINFERENCE']._serialized_start=532
  _globals['_LLMINFERENCE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
